### ISSUE TITLE
Schemas for PostgreSQL

### ISSUE THREAD

**Issue by coppermind** [ankane/blazer#106]
The role/user I'm testing this with already has a default search_path defined (and is working in the main rails app) but blazer is only loading the tables/views in `public`. 

Is there a config I'm overlooking on how to get blazer to get to load views and tables besides those in the public schema in PostgreSQL? Is this possible in the current version?

**Comment by ankane** [comment]
Hey @coppermind, you can use the `schemas` setting:

```
data_sources:
  source1:
    schemas:
      - public
      - other
```

https://github.com/ankane/blazer/blob/7f497e4e6db5297b24369afec26b0c19ff0581c8/lib/blazer/adapters/sql_adapter.rb#L114
