### ISSUE TITLE
Improve preview table dropdown by prefixing schema name when schemas options is used

### ISSUE THREAD

**Issue by kwent** [ankane/blazer#220]
Hi Andrew,

Using:

```yaml
data_sources:
  main:
    url: <%= ENV["BLAZER_RO_URL"] %>

    schemas:
      - public
      - schema1
      - schema2
      - schema3
```

Would be nice of there is an option to explicitly opt-in to prefix schema name even if table names are different through every schemas.
