### ISSUE TITLE
[Idea] Run Checks via ActiveJob Recurring

### ISSUE THREAD

**Issue by epugh** [ankane/blazer#488]
I recently successfully adopted SolidQueue for running some nightly jobs.  I'd love to reuse the definition in `recurring.yml` to also trigger the Checks instead of using heroku schedule or cron.

**Comment by epugh** [comment]
Digging around I found this:

https://github.com/ankane/blazer/issues/484#issuecomment-2508936081

**Comment by ankane** [comment]
Hi @epugh, from the Solid Queue docs, it looks like you can do:

```yml
production:
  blazer_run_checks_daily:
    command: "Blazer.run_checks(schedule: \"daily\")"
    schedule: every day at 8am
  blazer_send_failing_checks:
    command: "Blazer.send_failing_checks"
    schedule: every day at 9am
```
